# infra/secrets.yaml
Resources:
  GitHubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github-token
      Description: "GitHub Personal Access Token for CodePipeline"
      SecretString: !Sub "{{resolve:secretsmanager:github-token}}"

Outputs:
  GitHubTokenArn:
    Value: !Ref GitHubTokenSecret
    Export:
      Name: GitHubTokenArn
